name: CrashedTroll
version: 3.1.1
author: CrashedLife
main: de.crasheddevelopment.spigot.crashedtroll.CrashedTroll
commands:
  crashedtroll:
    description: "Main command of this plugin!"
    aliases:
      - troll
      - ct